name: build

on:
  push:
    paths-ignore:
      '.github/workflows/dist.yml'

jobs:
  win-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: build
      shell: pwsh
      run: |
        cmake -B build
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ./build/Release/axslcc.exe
        name: axslcc-win-x64
  win-arm64:
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v6
    - name: build
      shell: pwsh
      run: |
        cmake -B build -A arm64
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ./build/Release/axslcc.exe
        name: axslcc-win-arm64
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ./build/axslcc
        name: axslcc-linux-x64
  linux-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v6
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ./build/axslcc
        name: axslcc-linux-arm64
  osx-arm64:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v6
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4'
    - name: build
      shell: pwsh
      run: |
        cmake --version
        cmake -B build -DCMAKE_BUILD_TYPE=Release  -DCMAKE_OSX_ARCHITECTURES=arm64 "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
        cmake --build build --config Release --target axslcc
        $bin = Get-ChildItem -Recurse -Path build -Filter axslcc -File | Select-Object -First 1
        if (-not $bin) { throw "axslcc binary not found" }
        Write-Host "Binary found at: $($bin.FullName)"
        lipo -info $bin.FullName
        echo "binary-path=$($bin.FullName)" >> $env:GITHUB_OUTPUT
      id: build
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ${{ steps.build.outputs.binary-path }}
        name: axslcc-osx-arm64

  osx-x64:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v6
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4'
    - name: build
      shell: pwsh
      run: |
        cmake --version
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
        cmake --build build --config Release --target axslcc
        $bin = Get-ChildItem -Recurse -Path build -Filter axslcc -File | Select-Object -First 1
        if (-not $bin) { throw "axslcc binary not found" }
        Write-Host "Binary found at: $($bin.FullName)"
        lipo -info $bin.FullName
        echo "binary-path=$($bin.FullName)" >> $env:GITHUB_OUTPUT
      id: build
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        path: ${{ steps.build.outputs.binary-path }}
        name: axslcc-osx-x64
