name: build

on:
  push:
    paths-ignore:
      '.github/workflows/dist.yml'

jobs:
  win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: pwsh
      run: |
        cmake -B build
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./build/src/Release/axslcc.exe
        name: axslcc-win64
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target axslcc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./build/src/axslcc
        name: axslcc-linux
  osx-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
        cmake --build build --config Release --target axslcc
        lipo -info ./build/src/axslcc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./build/src/axslcc
        name: axslcc-osx-arm64

  osx-x64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
        cmake --build build --config Release --target axslcc
        lipo -info ./build/src/axslcc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./build/src/axslcc
        name: axslcc-osx-x64