name: build

on:
  push:
    paths-ignore:
      '.github/workflows/dist.yml'

jobs:
  win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      shell: pwsh
      run: |
        cmake -B build
        cmake --build build --config Release --target glslcc
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./build/src/Release/glslcc.exe
        name: glslcc-win64
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target glslcc
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./build/src/glslcc
        name: glslcc-linux
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: build
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target glslcc
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./build/src/glslcc
        name: glslcc-osx
